spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fullstack
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@123
  application:
    name: itineraryservice

server:
  port: 8083

logging:
  level:
    org.springframework: INFO
    com.yourpackage: DEBUG
